name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa
          python -m pip install --upgrade pip
          pip install setuptools-scm
          pip install .

      - name: Run tests
        run: |
          pytest
